---
title: "bdd-testthat"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{bdd-testthat}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  error = TRUE
)
```

```{r setup}
library(bddR)
```


```{r testthat, eval=FALSE}
if (!require(pak)) {
   install.packages("pak", 
     repos = "http://cran.us.r-project.org")
}
pak::pak("testthat")
library(testthat)
```

```{r}
testthat::test_that("
  Feature:
	  As a user
	  I want to see the changes in the plot
	  So that I can visualize the impact of my customizations
  ", code = {
  testthat::expect_true(TRUE)
})
```

```{r}
my_feature <- feature(
    As_a = "user",
    I_want = "to see the changes in the plot", 
   So_that = "I can visualize the impact of my customizations")
```

```{r}
my_feature
```

```{r}
class(my_feature)
```

```{r}
testthat::test_that(my_feature, code = {
  testthat::expect_true(TRUE)
})
```

```{r}
testthat::describe(
  feature(
    As_a = "user",
    I_want = "to see the changes in the plot", 
   So_that = "I can visualize the impact of my customizations"), 
  code = {
    testthat::it("
      Scenario: 
          Given 
          When 
          Then 
      ", code = {
      testthat::expect_true(TRUE)
    })
  })
```

```{r}
my_scenario <- scenario(
                 Given = "I have launched the application",
                 And = list("it contains movie review data from IMDB and Rotten Tomatoes",
                            "the data contains variables like 'Critics Score' and 'MPAA'"),
                 When = "I interact with the sidebar controls",
                 Then = "the graph should update with the selected options")
my_scenario
```


```{r}
testthat::describe(
  my_feature, 
  code = {
    testthat::it(my_scenario, 
      code = {
      testthat::expect_true(TRUE)
    })
  })
```

